#!/usr/bin/env python3
"""Optional Google Drive uploader for a LUPA backup.

This script is intentionally not run by CI or setup scripts. The repository
does not include OAuth credentials or tokens. Authentication only starts when
the repository owner executes this script on their own machine.
"""

from __future__ import annotations

import argparse
import mimetypes
from pathlib import Path

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

SCOPES = ["https://www.googleapis.com/auth/drive.file"]


def credentials(credentials_path: Path, token_path: Path) -> Credentials:
    """Load a saved token or launch the owner's OAuth flow when needed."""
    creds: Credentials | None = None
    if token_path.exists():
        creds = Credentials.from_authorized_user_file(str(token_path), SCOPES)
    if creds and creds.expired and creds.refresh_token:
        creds.refresh(Request())
    if not creds or not creds.valid:
        flow = InstalledAppFlow.from_client_secrets_file(str(credentials_path), SCOPES)
        creds = flow.run_local_server(port=0)
    token_path.write_text(creds.to_json(), encoding="utf-8")
    return creds


def create_folder(service, name: str, parent_id: str | None = None) -> str:
    metadata: dict[str, object] = {
        "name": name,
        "mimeType": "application/vnd.google-apps.folder",
    }
    if parent_id:
        metadata["parents"] = [parent_id]
    return service.files().create(body=metadata, fields="id").execute()["id"]


def upload_file(service, path: Path, parent_id: str) -> None:
    mime_type = mimetypes.guess_type(path.name)[0] or "application/octet-stream"
    media = MediaFileUpload(str(path), mimetype=mime_type, resumable=True)
    service.files().create(
        body={"name": path.name, "parents": [parent_id]},
        media_body=media,
        fields="id",
    ).execute()


def upload_tree(service, directory: Path, parent_id: str) -> None:
    for entry in sorted(directory.iterdir(), key=lambda item: item.name.lower()):
        if entry.name.startswith(".") or entry.name in {"node_modules", "dist", "build"}:
            continue
        if entry.is_dir():
            child_id = create_folder(service, entry.name, parent_id)
            upload_tree(service, entry, child_id)
        elif entry.is_file():
            upload_file(service, entry, parent_id)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Upload a structured LUPA backup to Google Drive.")
    parser.add_argument("--credentials", type=Path, required=True, help="OAuth desktop client JSON file.")
    parser.add_argument("--backup", type=Path, required=True, help="ZIP generated by create-backup.sh.")
    parser.add_argument("--source-root", type=Path, default=Path.cwd(), help="Repository root directory.")
    parser.add_argument("--token", type=Path, default=Path("token.json"), help="Local token file; keep it private.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not args.credentials.is_file():
        raise SystemExit(f"Credentials file not found: {args.credentials}")
    if not args.backup.is_file():
        raise SystemExit(f"Backup file not found: {args.backup}")

    service = build("drive", "v3", credentials=credentials(args.credentials, args.token))
    root_name = args.backup.stem
    drive_root_id = create_folder(service, root_name)
    upload_file(service, args.backup, drive_root_id)

    for name, source in {
        "src": args.source_root / "apps",
        "docs": args.source_root / "docs",
        "tests": args.source_root / "tests",
        "assets": args.source_root / "assets",
    }.items():
        if source.exists():
            folder_id = create_folder(service, name, drive_root_id)
            upload_tree(service, source, folder_id)

    print(f"Drive backup created: {root_name}")


if __name__ == "__main__":
    main()
